version: '3.8'

services:
  fishpond-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fishpond-app
    ports:
      - "8086:443"   # 前端 HTTPS 映射
      - "8085:80"    # 前端 HTTP (会被重定向)
      - "10086:10086"  # 后端 API
    volumes:
      - ./data:/app/backend/data.db  # 持久化数据库文件
      - ./certs:/etc/nginx/certs  # 挂载SSL证书目录
    environment:
      - AI_SERVICE_URL=http://fishpond-ai:10099  # AI 服务的地址
    restart: unless-stopped
    networks:
      - fishpond-network
    depends_on:
      - fishpond-ai

  fishpond-ai:
    build:
      context: .
      dockerfile: Dockerfile.ai
    container_name: fishpond-ai
    ports:
      - "10099:10099"  # AI 服务 API
    restart: unless-stopped
    networks:
      - fishpond-network

networks:
  fishpond-network:
    driver: bridge
